releases:
  - name: dex
    namespace: dex
    chart: dex/dex
    version: 0.14.3
    values:
      - config:
          issuer: https://dex.api.crc.testing:32000
          storage:
            type: kubernetes
            config:
              inCluster: true
          web:
            http: 0.0.0.0:5556
          grpc:
            addr: 0.0.0.0:5557
          oauth2:
            skipApprovalScreen: true
          connectors:
            - type: github
              id: github
              name: GitHub
              config:
                clientID: {{ requiredEnv "GITHUB_CLIENT_ID" }}
                clientSecret: {{ requiredEnv "GITHUB_CLIENT_SECRET" }}
                redirectURI: https://dex.api.crc.testing/callback
  