config:
  issuer: https://dex.api.crc.testing:32000
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: dexingress
    labels:
      name: dexingress
  spec:
    rules:
    - host: dex.api.crc.testing
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: dex
              port: 
                number: 5556
  
  storage:
    type: kubernetes
    config:
      inCluster: true
  web:
    http: 0.0.0.0:5556
  grpc:
    addr: 0.0.0.0:5557
  oauth2:
    skipApprovalScreen: true
  connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: $GITHUB_CLIENT_ID
        clientSecret: $GITHUB_CLIENT_SECRET
        redirectURI: https://dex.api.crc.testing/callback